import { CalendarCheck, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { Brand, ButtonLink, Card, PageShell, StatusPill } from "@/components/ui-kit";

const services = ["AI triage", "Media uploads", "Expert matching", "Live chat", "Admin controls", "Customer reviews", "Availability", "Secure access"];

export default function HomePage() {
  return <PageShell>
    <header className="border-b border-slate-200/70 bg-white/68 backdrop-blur-2xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><Brand/><div className="flex gap-2"><ButtonLink href="/login" variant="secondary">Login</ButtonLink><ButtonLink href="/signup">Start</ButtonLink></div></div></header>
    <section className="mx-auto grid min-h-[calc(100vh-74px)] max-w-7xl items-center gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_.92fr]">
      <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-teal-400/25 bg-teal-400/10 px-3 py-1 text-sm font-bold text-teal-700"><Sparkles size={15}/> LLM + NLP service intelligence</p><h1 className="max-w-3xl text-5xl font-black tracking-tight sm:text-6xl lg:text-7xl">Expert help, right when you need it.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Describe your issue, attach useful media, and let ExpertConnect AI classify it before connecting you with the right human expert.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/login">Create Issue</ButtonLink><ButtonLink href="/become-technician" variant="secondary">Become Expert</ButtonLink></div><div className="mt-8 flex flex-wrap gap-2"><StatusPill tone="good">Backend connected</StatusPill><StatusPill tone="info">JWT ready</StatusPill><StatusPill tone="warn">AI classify ready</StatusPill></div></div>
      <Card className="p-4"><div className="rounded-[1.2rem] bg-slate-950 p-5 text-white"><p className="text-sm opacity-70">Service journey</p><h2 className="mt-1 text-2xl font-black">From issue to expert</h2><div className="mt-8 grid gap-3">{[["1","Share your issue"],["2","Get intelligent triage"],["3","Connect with an expert"]].map(([number,label]) => <div key={number} className="flex items-center gap-4 rounded-2xl bg-white/10 px-4 py-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-teal-300 font-black text-slate-950">{number}</span><span className="font-bold">{label}</span></div>)}</div></div></Card>
    </section>
    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{services.map((service) => <Card key={service} className="p-5 font-bold">{service}</Card>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="grid gap-4 md:grid-cols-3">{[{ icon:<Wrench/>, title:"Report", text:"Share issue details and media after login." }, { icon:<ShieldCheck/>, title:"AI triage", text:"AI determines category and urgency." }, { icon:<CalendarCheck/>, title:"Assign", text:"Connect with the appropriate expert." }].map((item) => <Card key={item.title} className="p-6"><div className="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-teal-200 via-sky-200 to-violet-200 text-slate-950">{item.icon}</div><h3 className="font-black">{item.title}</h3><p className="mt-2 text-sm text-slate-600">{item.text}</p></Card>)}</div></section>
  </PageShell>;
}
