"""Add assignment fields

Revision ID: 3c287534ec4d
Revises: 02f0fe8dfc10
Create Date: 2026-07-03 11:33:44.043198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c287534ec4d'
down_revision: Union[str, Sequence[str], None] = '02f0fe8dfc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert_profiles', sa.Column('category', sa.String(), nullable=False))
    op.add_column('issues', sa.Column('assigned_expert_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['assigned_expert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'assigned_at')
    op.drop_column('issues', 'priority')
    op.drop_column('issues', 'assigned_expert_id')
    op.drop_column('expert_profiles', 'category')
    # ### end Alembic commands ###
