"""Add issue fields

Revision ID: ce8ed52fdc6d
Revises: 3c287534ec4d
Create Date: 2026-07-04 11:58:44.611232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8ed52fdc6d'
down_revision: Union[str, Sequence[str], None] = '3c287534ec4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expert_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('issues', sa.Column('preferred_visit_date', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('preferred_time', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('location', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('pin_code', sa.String(), nullable=True))
    op.alter_column('issues', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('issues', 'pin_code')
    op.drop_column('issues', 'address')
    op.drop_column('issues', 'location')
    op.drop_column('issues', 'preferred_time')
    op.drop_column('issues', 'preferred_visit_date')
    op.alter_column('expert_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
